export const cardItems = [
    {
        type: "experience",
        class:"trendyol",
        company: "Trendyol",
        position: "Associate Frontend Developer",
        date:"Jun. 2022 - Aug. 2022",
        location:"Istanbul-Turkey",
        logo:"",
        description:"• Developed a project from scratch to preprod with 5 other interns in the first month. • Taken part in the company’s web team meanwhile developing the intern project in the second month.",
    },
    {
        type: "experience",
        company: "eBay-GittiGidiyor",
        class:"gittigidiyor",
        position: "Frontend Developer Intern",
        date:"Jul. 2021 - Aug. 2021",
        location:"Istanbul-Turkey",
        logo:"",
        description:"Highly competitive internship placement where I was able to implement practices I learnt during my studies. Allowed me to gain real industry experience and put my skills to work on live projects.",
    },
    {
        type: "experience",
        company: "Kariyer.net",
        class:"kariyernet",
        position: "Bootcamp Attendee",
        date:"Mar. 2022 - Apr. 2022",
        location:"Online",
        logo:"",
        description:"After a competitive selection I was able to participate in the bootcamp. With this bootcamp I improved myself upon Back-End side of developement.",
    },
    {
        type: "education",
        class:"ytu",
        school: "Yildiz Technical University",
        position: "Bachelor Degree in Mathematical Engineering",
        date:"Sep. 2018 - Aug. 2022",
        location:"Istanbul-Turkey",
        logo:"",
        description:"Although we study mainly mathematics, we also study Software Development, Finance and Statistics. This is where I got into software development more and more.",
    },
    {
        type: "education",
        class:"erasmus",
        school: "Brno University   of Technology",
        position: "Bachelor Degree in Information Technology",
        date:"Sep. 2019 - Feb. 2020",
        location:"Brno-Czech Republic",
        logo:"",
        description:"VUT/BUT was the university I was studying in during my Erasmus. They introduced me to Java, Algorithms and HTML/CSS. We were a team of 4, they gave us a project for whole semester which I took responsibility of leadership.",
    },
]