export const projectItems = [
  {
    class: "ty-project",
    techClass:"ty-lang",
    section: "proje",
    type: "project",
    projectName: "Trendyol Form",
    technologies: "React • TypeScript • SCSS",
    githubLink: "",
    logo: "",
    description:"Google Form like project that takes dynamic input and validations with over 10 different components developed.",
  },
  {
    class: "pfr-project",
    techClass:"pfr-lang",
    section: "proje",
    type: "project",
    projectName: "Portfolio (With React)",
    technologies: "React • JavaScript • CSS",
    githubLink: "https://github.com/Aegean09/React-Portfolio",
    logo: "",
    description:"My own portfolio page. Practiced on Firebase",
  },
  {
    class: "ttt-project",
    techClass:"ttt-lang",
    section: "proje",
    type: "project",
    projectName: "Tic-Tac-Toe",
    technologies: "Angular • TypeScript • SCSS",
    githubLink: "https://github.com/Aegean09/Angular-Tic-Tac-Toe",
    logo: "",
    description: "Thesis project #2. Tic‑Tac‑Toe web‑page made with Angular in order to experience different frameworks. Experienced TypeScript language.",

  },
  {
    class: "pf-project",
    techClass:"pf-lang",
    section: "proje",
    type: "project",
    projectName: "Old Portfolio",
    technologies: "Html • Javascript • CSS • Bootstrap",
    githubLink: "https://github.com/Aegean09/Ege-Portfolio",
    logo: "",
    description: "Current portfolio website made with traditional html/css ways.Took reference from a random web page layout found on Wix.com to challenge HTML/CSS skills.",
  },
  {
    class: "jae-project",
    techClass:"jae-lang",
    section: "proje",
    type: "project",
    projectName: "JAE",
    technologies: "Html • Javascript • CSS • Bootstrap",
    githubLink: "https://github.com/leehuhlee/Web-Design",
    logo: "",
    description: "An imaginary restaurant web page that me and 3 other students from different nations made in Erasmus. Which I lead the project.",
  },
  {
    class: "mgc-project",
    techClass:"mgc-lang",
    section: "proje",
    type: "project",
    projectName: "Music Genre Classification",
    technologies: "Python • Deep/Machine Learning",
    githubLink: "https://github.com/Aegean09/Music-Genre-Classification",
    logo: "",
    description: "Thesis project #1. Classifiying music genres using Deep Learning algorithms, Feature Engineering methods and comparing performances of algorithms.",
  },
];
